name: CMSE495-TwoSix
channels:
  - conda-forge
  - bioconda
dependencies:
  - numpy
  - pandas
  - matplotlib
  - requests
  - ipykernel
  - conda-forge/label/python_rc::_python_rc
  - ca-certificates
  - certifi
  - openssl
  - pymongo
  - chromadb
  - bertopic
  - hdbscan
  - sentence-transformers
  - transformers
  - phate
  - textract
  - setuptools
  - jupyter
prefix: /home/emmaf/miniforge3/envs/CMSE495-TwoSix
