name: CMSE495-TwoSix
channels:
  - conda-forge
  - bioconda
  - anaconda
dependencies:
  - python=3.11
  - seaborn=0.13.2
  - chromadb=0.6.3
  - scikit-learn=1.6.1
  - bertopic=0.16.2
  - hdbscan=0.8.39
  - sentence-transformers=3.4.1
  - transformers=4.49.0
  - numpy=1.26
  - pymongo=4.11
  - jupyter=1.*
  - pytesseract=0.3.13
  - pandas=2.2.1
  - matplotlib=3.9.2
  - requests=2.32.2
  - pytesseract=0.3.13
  - pdf2image=1.17.0
  - ipykernel=6.28.0
  - pdf2image=1.17.0
  - phate=1.0.11
  - python-dotenv=1.1.0
  - spacy=3.7.4
  - nltk=3.8.1 
  - pip:
      - lmstudio==1.2.0
      - ujson
      - blingfire